id: PBD38FFC8
initial_creation_type: ocr
source_metadata:
  volumes:
    14cd5c45c8f24b8b84193879bc1fef37:
      base_file: v078.txt
      image_group_id: I1PD95923
      title: སྡོམ་པ་ཉི་ཤུ་པའི་འགྲེལ་པ།
      total_pages: 1254
      volume_number: 78
