id: DF3AA9BD6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T06:47:38+00:00'
last_modified: '2022-05-29T08:44:56.905693+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    d213:
      image_group_id: I1PD95923
      title: སྡོམ་པ་ཉི་ཤུ་པའི་འགྲེལ་པ།
      total_pages: 1254
      order: 78
      base_file: d213.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
